### ISSUE TITLE
AST

### ISSUE THREAD

**Issue by CoconutNutNut** [AureumApes/Aureum-Script-Interpreter-Kotlin#1]
Switch from manual interpreting to an AST interpreter.
Why the switch?
Well, an AST interpreter helps you maintain high performance, while also increases readability and maintainability of the code of the interpreter.
AST also simplifies the amount of work needed to add a new feature to the code bases, as you don't have to hard code the syntax line by line.

**Comment by AureumApes** [comment]
Do this in a firk pls.
We want the original Version of the Interpreter here

**Comment by AureumApes** [comment]
We want the original here.
Do this in a fork.
I will put it in the readme as trustet fork

**Comment by AureumApes** [comment]
We want the original here.
Do this in a fork.
I will put it in the readme as trustet fork

**Comment by CoconutNutNut** [comment]
well. But it would make the language more efficient.
